### ISSUE TITLE
fix JSON readin in MATLAB2017

### ISSUE THREAD

**Issue by rhiju** [ribokit/RiboDraw#21]
our JSON read/write package `jsonlab-1.5` fails in 2017.  This may be fixed in:
https://github.com/fangq/jsonlab

**Comment by everyday847** [comment]
I can address this one, I think.

**Comment by everyday847** [comment]
Testing this, I can't reproduce because just initializing a drawing based on a PDB (in a place where I've previously made ribodraw work; there's for sure `rna_motif` output in this directory etc.) I get:

```
Error in set_nice_axes (line 15)
pos = plotboxpos;
```

**Comment by rhiju** [comment]
that looks like a typo. I haven’t run initialize_drawing in a while — can you comment that out and see if you can get things working? and please commit via a separate pull request if that does the fix. R
On Apr 23, 2018, at 1:54 PM, Andy Watkins <notifications@github.com<mailto:notifications@github.com>> wrote:


Testing this, I can't reproduce because just initializing a drawing based on a PDB (in a place where I've previously made ribodraw work; there's for sure rna_motif output in this directory etc.) I get:

Error in set_nice_axes (line 15)
pos = plotboxpos;

**Comment by everyday847** [comment]
Ah, yes. This is the error I think I remember last time we tracked this down:

```
Error using isappdata
Second argument must be a character vector

Error in cleanup_domains (line 21)
        if ~isappdata( gca, selection )

Error in load_drawing (line 94)
cleanup_domains();
```

If I remember correctly, `selection` is getting loaded in as some other kind of object due to how string parsing works. I think I am up to date mentally on troubleshooting this.

**Comment by everyday847** [comment]
Aha, you have a solution to this already. Whoops!

**Comment by rhiju** [comment]
Wait no, I don't quite have a solution to this. I have some useful commits in PR #23, but as I have commented in your PR #24, I think our work is complementary and only taken together accomplish the complete fix to JSON i/o !

**Comment by everyday847** [comment]
Interesting -- it actually looked like your fix was working 100% on my
json, but maybe it was just a simple case. Cool, glad to have contributed.

**Comment by rhiju** [comment]
> Testing this, I can't reproduce because just initializing a drawing based on a PDB (in a place where I've previously made ribodraw work; there's for sure rna_motif output in this directory etc.) I get:

> Error in set_nice_axes (line 15)
pos = plotboxpos;

@everyday847  I realized what the issue is here -- you need to Add paths again, as I added a new package to `scripts/externals/` to try to ameliorate some of the axis setting craziness. Axis settings and updatinga are still  not quite to my satisfaction, but at least we have this `plotboxpos` package in the repo for testing more later.
