### ISSUE TITLE
Output to `.svg`

### ISSUE THREAD

**Issue by rhiju** [ribokit/RiboDraw#5]
The m-file is `export_drawing` -- now handles jpg, png, ps, pdf, but not svg.

Here's the library:
https://www.mathworks.com/matlabcentral/fileexchange/7401-scalable-vector-graphics--svg--export-of-figures

**Comment by rhiju** [comment]
@everyday847 in case you wanted to contribute something super-quick that would help us get the 23S RNA annotated with Do Soon's data.

**Comment by everyday847** [comment]
absolutely will do

**Comment by rhiju** [comment]
this SVG issue seems closed.

**Comment by rhiju** [comment]
this SVG issue seems closed.

**Comment by everyday847** [comment]
yes it is, good catch
