### ISSUE TITLE
Initialization from secstruct alone (no PDB)

### ISSUE THREAD

**Issue by rhiju** [ribokit/RiboDraw#7]
Allow initialization from sequence and secstruct.
I wonder if we should also include a better heuristic for the initial helix layout too.
Could potentially also allow helices to get laid out along directions that are not horizontal/vertical, like in VARNA, FORNA, eterna, etc.

**Comment by rhiju** [comment]
Almost complete with new `initialize_drawing` mode that accepts just `.fasta` and `.stems.txt` to get going. Check out https://github.com/ribokit/RiboDraw/commit/de8a9fde167bdc449f04bac968da28518af80285

**Comment by everyday847** [comment]
oh this is fantastic!

**Comment by rhiju** [comment]
Did this! And added info in tutorial.
